name: Build & Deploy to gh-pages
on: [push]
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - '*'

jobs:
  build_job:
    name: build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Build blog
        run: |
          docker run --rm \
          --user 1001 \
          -v $(pwd):/src \
          -w /src \
          ruby:2.6.4 \
          /bin/bash -c 'bundle install && bundle exec jekyll build --verbose --destination "_site"'
      - name: Build CV
        run: |
          docker run --rm \
          --user 1001 \
          -v $(pwd)/cv:/data pandoc/latex --standalone -c style.css --from markdown --to html -o cv.html cv.md
          ls -la $(pwd)
          ls -la $(pwd)/cv/
          cp $(pwd)/cv/cv.html _site/cv/
          cp $(pwd)/cv/style.css _site/cv/
          ls -la ./_site
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with: 
          name: _site
          path: _site/
  deploy_job:
    if: github.event_name == 'push' &&  github.ref == 'master'
    needs: build_job
    name: deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
      - name: Get the build artifact
        uses: actions/download-artifact@v1
        with:
          name: _site
          path: ./
      - name: Deploy (push) to gh-pages
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@bots.github.com"
          git add -A 
          git commit -a -m "updated GitHub Pages"
          git remote set-url origin "https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/vasylenko/serhii.vasylenko.info.git"
          git push --force-with-lease origin gh-pages