name: CV
on:
  push:
    branches: 
      - master
    paths: 
      - 'cv/**'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build CV
        run: |
          mkdir _site
          docker run --rm \
          --user 1001 \
          -v $(pwd)/cv:/data pandoc/latex --standalone -H head.html --from markdown --to html5 -o index.html cv.md
          cp -r $(pwd)/cv _site

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with: 
          name: _site
          path: _site/

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
      - name: Get the build artifact
        uses: actions/download-artifact@v1
        with:
          name: _site
          path: ./
      - name: Deploy (push) to gh-pages
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@bots.github.com"
          git add -A 
          git commit -a -m "Updated CV"
          git remote set-url origin "https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/vasylenko/serhii.vasylenko.info.git"
          git push --force-with-lease origin gh-pages