name: Website
on:
  push:
    paths:
      - '_includes/**'
      - '_layouts/**'
      - '_posts/**'
      - 'assets/**'
      - '*'
      - '.github/workflows/website.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: svasylenko/jekyllbuilder:latest
      env:
        LANG: "en_US.UTF-8"
        LANGUAGE: "en_US:en"
        LC_ALL: "en_US.UTF-8"
    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: Build blog
        run: |
          bundle install
          bundle exec jekyll build --verbose --destination _site
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: _site
          path: _site

  deploy:
    if: github.ref == 'refs/heads/new-theme'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages-new-theme'

      - name: Get the build artifact
        uses: actions/download-artifact@v2
        with:
          name: _site
          path: ./

      - name: Deploy (push) to gh-pages
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@bots.github.com"
          git add -A 
          git commit -a -m "Updated Website"
          git remote set-url origin "https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/vasylenko/serhii.vasylenko.info.git"
          git push --force-with-lease origin gh-pages-new-theme