name: Workflow
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name
    name: Job name
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Step - Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Planet Earth'
        id: id_hello
      # This step prints an output (time) from the previous step's action.
      - name: Step - tell the date and list files
        run: |
          echo '$(date)'
          ls -la 