name: Workflow
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build_job:
    name: build job
    runs-on: ubuntu-latest
    steps:
      - name: Step#0 - facts
        run: |
          whoami
          id
          pwd
      - name: Step#1 - checkout
        uses: actions/checkout@v2 
      # - name: Run Jekyll
      #   uses: docker://faph/action-jekyll
      #   with:
      #       add_nojekyll_tag: false
      - name: Step#3 - build
        run: |
          docker run \
          --user 1001 \
          -v $(pwd):/src \
          -w /src \
          ruby:2.6.4 \
          bundle install ; pwd ; ls -la ; bundle exec jekyll build --verbose --destination "_site"
      - name: Step#4 - upload artifact
        uses: actions/upload-artifact@v1
        with: 
          name: _site
          path: _site/
  deploy_job:
    needs: build_job
    name: deploy job
    runs-on: ubuntu-latest
    steps:
      - name: step#1
        run: |
          echo "this would be a deploy job"
