name: Workflow
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build_job:
    # Job name
    name: build job
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Step#1 - checkout
        uses: actions/checkout@v2
      - name: Step#2 - build
        run: |
          docker run --rm --volume="$PWD:/srv/jekyll" -it jekyll/builder jekyll build
          echo "$(pwd && ls -la _site)"
      - name: Step#3 - prepare artifact
        run: zip -r _site.zip _site
      - name: Step#4 - upload artifact
        uses: actions/upload-artifact@v1
          with: 
            name: _site
            path: ./_site.zip
  deploy_job:
    needs: build_job
    name: deploy job
    runs-on: ubuntu-latest
    steps:
      - name: step#1
        run: |
          echo "this would be a deploy job"
