name: Workflow
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build_job:
    # Job name
    name: build job
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: step#1 - checkout
        uses: actions/checkout@v2
        with:
          path: folder
      - name: step#2 - list files
        run: |
          echo "$(date)"
          echo "$(pwd && ls -la -R)"
  deploy_job:
    needs: build_job
    name: deploy job
    runs-on: ubuntu-latest
    steps:
      - name: step#1
        run: |
          echo "this would be a deploy job"
