name: Workflow
on:
  push:
    branches:
    - master

jobs:
  build_job:
    name: build job
    runs-on: ubuntu-latest
    steps:
      - name: Step#0 - facts
        run: |
          whoami
          id
          pwd
      - name: Step#1 - checkout
        uses: actions/checkout@v2 
      - name: Step#3 - build
        run: |
          docker run \
          --user 1001 \
          -v $(pwd):/src \
          -w /src \
          ruby:2.6.4 \
          /bin/bash -c 'bundle install && bundle exec jekyll build --verbose --destination "_site"'
      - name: Step#4 - upload artifact
        uses: actions/upload-artifact@v1
        with: 
          name: _site
          path: _site/
  deploy_job:
    needs: build_job
    name: deploy job
    env:
      repo_uri: "https://x-access-token:${DEPLOY_TOKEN}@github.com/serhii.vasylenko.info.git"
      target_branch: "gh-pages"

    runs-on: ubuntu-latest
    steps:
      - name: Step - checkout gh-pages branch
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@bots.github.com"
          git checkout gh-pages
          ls -la
      - name: step - get the build
        uses: actions/download-artifact@v1
        with:
          name: _site
          path: ./
      - name: check
          run: |
            pwd
            ls -la ./